# action.yml
name: 'Terraform Helm Updater'
description: 'Updates Helm versions in Terraform modules'
inputs:
  working-directory:
    description: 'Directory to run the action in (must be a Git repository)'
    required: true
    default: "/github/workspace"
  chart-file:
    description: 'Name of the file with the chart versions (default chart.yaml'
    required: true
    default: "charts.yaml"
  main-branch:
    description: 'Name of the main branch in the repository'
    required: true
    default: "main"
runs:
  using: 'docker'
  image: "Dockerfile"
  env:
    WORKING_DIRECTORY: ${{ inputs.working-directory }}
    CHART_FILE: ${{ inputs.chart-file }}
    MAIN_BRANCH: ${{ inputs.main-branch }}